output "cluster_info" {
  description = "High-level cluster metadata"
  value = {
    name              = module.homelab_example.cluster_name
    endpoint          = module.homelab_example.cluster_endpoint
    control_plane_ips = module.homelab_example.control_plane_ips
    worker_ips        = module.homelab_example.worker_ips
  }
}

output "vm_info" {
  description = "Proxmox VM identifiers used for the cluster"
  value       = module.homelab_example.vm_info
}

output "kubeconfig" {
  description = "Raw kubeconfig generated by Talos"
  value       = module.homelab_example.kubeconfig
  sensitive   = true
}

output "talosconfig" {
  description = "Talos client configuration"
  value       = module.homelab_example.talosconfig
  sensitive   = true
}
